language: python

python:
    - "2.6"
    - "2.7"

branches:
  only:
    - master

before_script:
    - pip install jieba
    - cd tgrocery/learner
    - make

script:
    - cd -
    - python runtests.py
